name: The Grassy Hopper
favicon: null
layout_spectrum: 0.2811056491918862
typography_spectrum: 0.24727187235839665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3315827460028231
  lightness: 0.33798922039568424
  saturation: 0.9098862432874739
  rhythmicContrast: 0.2580855342093855
purpose: []
