name: The Grassy Hopper
favicon: null
layout_spectrum: 0.74904
typography_spectrum: 0.24727187235839665
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe4de'
    - '#040500'
    - '#2a6a36'
    - '#ac6a5e'
    - '#42ba96'
  brandStrength: 0.5
  lightness: 0.33798922039568424
  saturation: 0.9098862432874739
  rhythmicContrast: 0.2580855342093855
purpose: []
